services:

  # Backend service
  Django:
    image: django
    container_name: django
    build: ./backend/services/Django
    depends_on:
      - PostgreSQL
      - redis
    volumes:
      - ./backend/services/Django:/app
    restart: always
    networks:
      - Ft_Transcendence
    secrets:
      - postgres_password
      - django_superuser
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=ft_transcendence_user
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_HOST=postgres

  # Database service
  PostgreSQL:
    image: postgres:17.2
    container_name: postgres
    restart: always
    networks:
      - Ft_Transcendence
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    secrets:
      - postgres_password
    environment:
      - POSTGRES_DB=ft_transcendence_db
      - POSTGRES_USER=ft_transcendence_user
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password

  nginx:
    image: nginx
    container_name: nginx
    build: ./backend/services/nginx
    depends_on:
      - Django
    ports:
      - "443:443" #random ports
    restart: always
    networks:
      - Ft_Transcendence
    volumes:
      - ./frontend:/var/www/transcendence
      - ./backend/services/nginx/certs:/etc/nginx/certs
      - ./backend/services/Django/media:/var/www/transcendence/media
      - ./backend/services/Django/static_files:/var/www/transcendence/static
    environment:
      - DOMAIN=transcendence.de

  redis:
    image: redis:7.4.2
    container_name: redis
    restart: always
    networks:
      - Ft_Transcendence

volumes:
  postgres_volume:
    name: postgres_volume
    driver: local

networks:
  Ft_Transcendence:
    name: transcendence
    driver: bridge

secrets:
  postgres_password:
    file: ./secrets/postgres_password.env
  django_superuser:
    file: ./secrets/django_superuser.env
